### ISSUE TITLE
Create the design system

### ISSUE THREAD

**Issue by Capure** [bajton/bajton#23]
What should be done:
 - Decide on the design system
 - Attach a figma file to this issue

**Comment by NightfallHT** [comment]
Colors:
https://www.figma.com/file/QZ32sJwqbpJVZumFiY8vPq/Styles?type=design&node-id=0-1&t=FRBRHVF1d5Zy8O59-0
Typography:
https://www.figma.com/file/QZ32sJwqbpJVZumFiY8vPq/Styles?type=design&node-id=36-263&mode=design&t=ssoTthPJOl9rKigT-0
